
GET http://localhost:8045/tasks?assignee=1

###

# curl -X POST  http://localhost:8080/process
POST http://localhost:8045/process

###
# curl http://localhost:8080/tasks?assignee=kermit
GET http://localhost:8045/tasks?assignee=kermit

###
# curl -H "Content-Type: application/json" -d '{"assignee" : "jbarrez"}' http://localhost:8080/process
POST http://localhost:8045/process
Content-Type: application/json

{
  "assignee": "jbarrez"
}

###

# curl http://localhost:8080/actuator/flowable
GET http://localhost:8045/actuator/flowable

###

GET http://localhost:8045/actuator/info

###







