spring:
  application:
    name: flowableLearn
  datasource:
    url: jdbc:mysql://49.234.132.208:3306/flowable_app?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
#  devtools:
#    add-properties: false
server:
  port: 8045
flowable:
  check-process-definitions: true
springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
  api-docs:
    path: /openapi/v3/api-docs
  packages-to-scan: com.example.flowableexample.controller
  paths-to-match: /**
management:
  endpoints:
    web:
      exposure:
        include: flowable

